services:
  stock-backend:
    build:
      context: .
      dockerfile: backend.dockerfile
    image: stock-backend:main
    ports:
      - 3001:3001
    volumes:
      - backend-dbstore:/home/stock/data
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    networks:
      - stock-network
    env_file:
      - .env
    restart: unless-stopped

  stock-frontend:
    build:
      context: .
      dockerfile: app.dockerfile
      args:
        - NEXT_PUBLIC_API_URL=http://127.0.0.1:3001/api
        - NEXT_PUBLIC_WS_URL=ws://127.0.0.1:3001
    image: stock-frontend:main
    depends_on:
      - stock-backend
    ports:
      - 3000:3000
    networks:
      - stock-network
    restart: unless-stopped

networks:
  stock-network:

volumes:
  backend-dbstore:
